name: plastic_counter
description: Application to encourage you to reduce your carbon footprint

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  json_serializable: ^3.0.1
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.18
  easy_rich_text: '^0.5.2'
  charts_flutter: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/forrest.jpeg
    - assets/images/recycle_city_background.jpeg
    - assets/images/tree_for_data.jpg
    - assets/images/sapling.png
    - assets/images/young_tree.png
    - assets/images/acre.png
    - assets/images/mycfoot.png
    - assets/images/logo.png
    - assets/images/info_bg.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
